[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "dark"
backgroundColor = "#06060f"
secondaryBackgroundColor = "#0d0d22"
primaryColor = "#5555cc"
textColor = "#d0d0f0"

[browser]
gatherUsageStats = false
